services:
  web:
    build: .
    env_file: .env
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app   # mount your local project into /app in the container
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DJANGO_AUTORELOAD_ENV: watchdog
      PYTHONUNBUFFERED: "1"

  celery:
    build: .
    env_file: .env
    command: celery -A core worker -l info
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONUNBUFFERED: "1"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
