services:
  web:
    build: .
    env_file: .env
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      # - redis
      redis:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - .:/app   # mount your local project into /app in the container
      # - ./entrypoint.sh:/app/entrypoint.sh  # explicit re-mount
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DJANGO_AUTORELOAD_ENV: watchdog
      PYTHONUNBUFFERED: "1"

  celery:
    build: .
    env_file: .env
    command: celery -A core worker -l info
    depends_on:
      - redis
    volumes:
      - .:/app
      # - ./entrypoint.sh:/app/entrypoint.sh  # explicit re-mount
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONUNBUFFERED: "1"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ovena
      POSTGRES_USER: ovena
      POSTGRES_PASSWORD: ovena
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ovena -d ovena -h localhost -p 5432"]
      interval: 3s
      timeout: 3s
      retries: 30

  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   depends_on:
  #     - web

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=supersecurepassword